apiVersion: v1
kind: Config
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURKekNDQWcrZ0F3SUJBZ0lDQm5Vd0RRWUpLb1pJaHZjTkFRRUxCUUF3TXpFVk1CTUdBMVVFQ2hNTVJHbG4KYVhSaGJFOWpaV0Z1TVJvd0dBWURWUVFERXhGck9ITmhZWE1nUTJ4MWMzUmxjaUJEUVRBZUZ3MHlNakEyTVRJdwpNekF6TlRoYUZ3MDBNakEyTVRJd016QXpOVGhhTURNeEZUQVRCZ05WQkFvVERFUnBaMmwwWVd4UFkyVmhiakVhCk1CZ0dBMVVFQXhNUmF6aHpZV0Z6SUVOc2RYTjBaWElnUTBFd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUIKRHdBd2dnRUtBb0lCQVFDbG1UQTZSNFZqbkJaTERrZ0laTTJBeGZ1SUNHU3Z1MzUydncvT3h3eXdDT1g3L1Y1QQpGWGsramU0TVIwN29Fb1JjNDRYSWQrT3oxWksrRGV1R1JGMUFBU0cxdWYyb0JQR09xOWZRNS82c2V1dUM2Tmh2Cml0aEFTS1dOblFPS3J3YnhlRVdJR1o5bmx6RFZFUTVrbmVaRTlMMTVlTlBuRjdHQ2p6eDQ2T1gwNlhCWmFQaTQKWUZIdmh1SzN6elg4SzBqKzVFN1ZtNGpiMTJ2WGcwMWJtTFdWY3JSTTB0bUJZcDl0dUlWSWZ3NVFyM0xmaUFRKwpaeTA3ZDF2dlUwWlhzYzRxRERYYWhOY2M4QmIwWVFUbGJkTHNlaS9MWXZTR0pEdWJXckxFMmY4aHYxVnVzRXdoCisrbEZvMEh1RC9oK3QxdEErQ09jcWp3enJRSTZBVXVXTC9qTkFnTUJBQUdqUlRCRE1BNEdBMVVkRHdFQi93UUUKQXdJQmhqQVNCZ05WSFJNQkFmOEVDREFHQVFIL0FnRUFNQjBHQTFVZERnUVdCQlF6YVJsSUVOeXNNMVUxSER3NQpuSGFuMmFZSWREQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFYTWxHcm9TM1RWWGRaT1VRNzhpZGxhamZSQjRLCnozUHNJTzg4Vm11S2w5MGxOR3lsRHJaNFV3OXBLUFhtenR0L0E3RysxTHArbURpSEZPeGFWb2VHb2NmTVh2VzgKR3RveDg4UnJJVlI5OGhPZ09ZYm5tcElUZFRpSExtMEJ4NE02c21VRDFtVGZRRTkzWU8yRlRTWDFubnB2Wi85YgpvNnduUm5FbTJYMmdnR0dFSVJVSFV1aTE4SWtMR2NHUTJmY1RoQk5TYUlqOTkvWDJ2MTdzVXN1VGI1cDRYU045Cmg4dGF5WFFKTi9iNG9sdTlYSkpCa1hBaVN4aC95T09BZm1Oalp3dlNGT3pPTkRka1QyOEhVM1o4c1p4RWZNVFkKVmFIRXJOOHVhc05mdndCdE42YjFPOUgxVUg3S2ZrR3B6WllSdG1ITFZxNGNQK0swTVNuYVBjdW1GZz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://6fef0265-4241-4e4f-9dbd-0d1db9fba450.k8s.ondigitalocean.com
  name: do-nyc1-k8s-iniciativa-deveops
contexts:
- context:
    cluster: do-nyc1-k8s-iniciativa-deveops
    user: do-nyc1-k8s-iniciativa-deveops-admin
  name: do-nyc1-k8s-iniciativa-deveops
current-context: do-nyc1-k8s-iniciativa-deveops
users:
- name: do-nyc1-k8s-iniciativa-deveops-admin
  user:
    token: dop_v1_711d626228a227c07b16d7ed01c0ea851417a811fc66f66f035f1a81457e2f8b
